# Warning: the .env file feature only works when you use the "docker-compose up" 
# command and does not work with docker stack deploy.

version: '3'
services:
  mariadb:
    image: mariadb
    container_name: "mariadb"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_DOCKER_PASS
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    volumes:
      - ./data:/var/lib/mysql

  hemengo-api:
    image: hemengo-api:latest
    container_name: "hemengo-api"
    build: .
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      DB_HOST: "mariadb"
      DB_PORT: 3306
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_DOCKER_PASS
      JWT_SECRET: $JWT_SECRET
      JWT_DURING: $JWT_DURING
      BCRYPT_SALT_ROUND: $BCRYPT_SALT_ROUND
    depends_on:
      - mariadb
